<section class="row mt-5">
    <div class="col-md-4 offset-md-4">
        <div class="card card-body">
            <form action="" method="post">
                <label for="email">Email</label>
                <input name="email" id="name" type="email" placeholder="Email" class="form-control form-control-lg mb-3">
                <label for="senha">Senha</label>
                <input name="senha" id="senha" type="password" placeholder="Senha" class="form-control form-control-lg mb-3">
                <div class="d-grid">
                    <button class="btn btn-dark btn-lg">Entrar</button>
                </div>
            </form>
        </div>
    </div>
</section>