<section class="mt-3 card card-body">
    <h1>Gerenciar Professores</h1>
    <div class="mt-2">
        <a href="/alunos/novo" class="btn btn-outline-dark">Novo Professor</a>
    </div>
    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>Endereço</th>
                <th>Status</th>
                <th>Horario Disponivel</th>
                <th>Formação</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</section>