<section class="mt-3 card card-body">
    <h1>Gerenciar Professores</h1>
    <div class="mt-2">
        <a href="/professores/novo" class="btn btn-outline-dark">Novo Professor</a>
        <a href="/professores/relatorio" target="_blank" class="btn btn-outline-dark">Gerar PDF</a>
    </div>
    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>Endereço</th>
                <th>Status</th>
                <th>Formação</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if(isset($professores)&& sizeof($professores) > 0){
                foreach($professores as $professor){
                    echo"
                        <tr>
                            <td>{$professor->id}</td>
                            <td>{$professor->nome}</td>
                            <td>{$professor->cpf}</td>
                            <td>{$professor->endereco}</td>
                            <td>{$professor->status}</td>
                            <td>{$professor->formacao}</td>
                            <td>
                                <a href='/professores/editar?id={$professor->id}' class='btn btn-outline-warning'>Editar</a>
                                <button type='button' class='btn btn-danger' data-bs-toggle='modal' data-bs-target='#modalexcluir' onclick='pegarID({$professor->id})'>Excluir</button>
                            </td>
                        </tr>
                    ";
            }
            }
            ?>
        </tbody>
    </table>
</section>
<div class='modal fade' id='modalexcluir' tabindex='-1' aria-labelledby='exampleModalLabel' aria-hidden='true'>
    <div class='modal-dialog'>
        <div class='modal-content'>
            <div class='modal-header'>
                <h1 class='modal-title fs-5' id='exampleModalLabel'>Apagar Professor</h1>
                <button type='button' class='btn-close' data-bs-dismiss='modal' aria-label='Close'></button>
            </div>
            <div class='modal-body'>
                DESEJA APAGAR ESTE PROFESSOR?
                <input type="hidden" id="idatual">
            </div>
            <div class='modal-footer'>
                <button type='button' class='btn btn-secondary' data-bs-dismiss='modal'>Cancelar</button>
                <button type='button' onclick='confirmar()' class='btn btn-danger'>Confirmar</button>
            </div>
        </div>
    </div>
</div>
<script>
    function pegarID(id){
        document.getElementById("idatual").value = id;
    }
    function confirmar(){
        if(true === confirm('Tem certeza mesmo?')){
            id= idatual.value;
            location.href = '/professores/excluir?id='+id;
        }
    }
</script>