<?php
    date_default_timezone_set('America/Fortaleza');
    $hoje = date('d/m/Y \à\s H:i:s');
?>
<html>
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<h1 class="text-center"> Relatório de Professores </h1>        
        <hr>
        <div class="table-responsive">
    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark" style="border-bottom:1px solid black">
        <tr>
            <th>#ID</th>
            <th>Nome</th>
            <th>CPF</th>
            <th>Formação</th>
            <th>Endereço</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        <?php
            function renderizar(iterable $professores)
            {
                $resultado = '';
                foreach($professores as $professor){
                    $resultado .= "
                    <tr>
                        <td>{$professor->id}</td>
                        <td>{$professor->nome}</td>
                        <td>{$professor->cpf}</td>
                        <td>{$professor->formacao}</td>
                        <td>{$professor->endereco}</td>
                        <td>{$professor->status}</td>
                    </tr>
                    ";
                    return $resultado;
                }
            }
    ?>
    </tbody>
    </table>
        <p class="text-center" > Gerado em <?php echo $hoje; ?></p>
</body>
</html>