<section class="mt-3 card card-body">
    <h1>Editar Usuario</h1>
    <div class="row">
        <div class="col">
            <form action="#" method="POST">
                <label for="nome">Nome</label>
                <input type="text" name="nome" id="nome" class="form-control mb-3" value="<?php echo $dados[0]->nome ?>">
                <label for="email">Email</label>
                <input type="email" name="email" id="email" class="form-control mb-3" value="<?php echo $dados[0]->email ?>">
                <label for="perfil">Perfil</label>
                <input type="text" name="perfil" id="perfil" class="form-control mb-3" value="<?php echo $dados[0]->perfil ?>">
                <button type="submit" class="btn btn-primary">Pronto</button>
            </form>
        </div>
    </div>
</section>