<section class="mt-3 card card-body">
    <h1>Gerenciar Usuarios</h1>

    <div class="mt-2">
        <a href="/usuarios/novo" class="btn btn-outline-dark">Novo Usuario</a>
        <a href="/usuarios/relatorio" target="_blank" class="btn btn-outline-dark">Gerar PDF</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Perfil</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach ($usuarios ?? [] as $usuario) {
                    echo "
                        <tr>
                            <td>{$usuario->id}</td>
                            <td>{$usuario->nome}</td>
                            <td>{$usuario->email}</td>
                            <td>{$usuario->perfil}</td>
                            <td>
                                <a href='/usuarios/editar?id={$usuario->id}' class='btn btn-outline-warning btn-sm'>Editar</a>
                                <a href='/usuarios/excluir?id={$usuario->id}' class='btn btn-outline-danger btn-sm'>Excluir</a>
                            </td>
                        </tr>
                    ";
                }
            ?>
        </tbody>
    </table>
</section>