<section class="mt-3 card card-body">
    <h1>Novo Curso</h1>
    <div class="row">
        <div class="col">
            <form action="#" method="POST">
                <label for="nome">Nome</label>
                <input type="text" name="nome" id="nome" class="form-control mb-3" value="<?php echo $dados[0]->nome; ?>">
                <label for="cargaHoraria">Carga Horária</label>
                <input type="text" name="cargaHoraria" id="cargaHoraria" class="form-control mb-3" value="<?php echo $dados[0]->cargaHoraria; ?>">
                <label for="descricao">Descrição</label>
                <input type="text" name="descricao" id="descricao" class="form-control mb-3" value="<?php echo $dados[0]->descricao; ?>">
                <label for="categoria">Categoria</label>
                <input type="text" name="categoria" id="categoria" class="form-control mb-3" value="<?php echo $dados[0]->categoria; ?>">
                <button type="submit" class="btn btn-primary">Pronto</button>
            </form>
        </div>
    </div>
</section>